ARDUINO_ROOT = C:/ProgramData/MATLAB/SupportPackages/R2024a/aCLI
export ARDUINO_ROOT
ARDUINO_TARGET_ROOT = C:/ProgramData/MATLAB/SupportPackages/R2024a/toolbox/target/supportpackages/arduinotarget
export ARDUINO_TARGET_ROOT
ARDUINO_IDE_VERSION = 10819
export ARDUINO_IDE_VERSION
ARDUINO_AVR_ROOT = C:/ProgramData/MATLAB/SupportPackages/R2024a/aCLI/data/packages/arduino
export ARDUINO_AVR_ROOT
AVR_LIB_VERSION = 1.8.3
export AVR_LIB_VERSION
AVR_GCC_LIB_VERSION = 7.3.0-atmel3.6.1-arduino7
export AVR_GCC_LIB_VERSION
ARDUINO_SAM_ROOT = C:/ProgramData/MATLAB/SupportPackages/R2024a/aCLI/data/packages/arduino
export ARDUINO_SAM_ROOT
SAM_LIB_VERSION = 1.6.12
export SAM_LIB_VERSION
ARDUINO_SAMD_ROOT = C:/ProgramData/MATLAB/SupportPackages/R2024a/aCLI/data/packages/arduino
export ARDUINO_SAMD_ROOT
SAMD_CMSIS_VERSION = 4.5.0
export SAMD_CMSIS_VERSION
SAMD_CMSIS_ATMEL_VERSION = 1.2.0
export SAMD_CMSIS_ATMEL_VERSION
SAMD_LIB_VERSION = 1.8.9
export SAMD_LIB_VERSION
ARDUINO_MBED_ROOT = C:/ProgramData/MATLAB/SupportPackages/R2024a/aCLI/data/packages/arduino
export ARDUINO_MBED_ROOT
MBED_CMSIS_VERSION = 4.5.0
export MBED_CMSIS_VERSION
MBED_CMSIS_ATMEL_VERSION = 1.2.0
export MBED_CMSIS_ATMEL_VERSION
MBED_LIB_VERSION = 1.3.2
export MBED_LIB_VERSION
ARDUINO_CODEGEN_FOLDER = C:/Users/kzlee/Desktop/FRS24/FRS24_SIMULINK/untitled1_ert_rtw
export ARDUINO_CODEGEN_FOLDER
ARDUINO_ESP32_ROOT = C:/ProgramData/MATLAB/SupportPackages/R2024a/aCLI/data/packages/esp32
export ARDUINO_ESP32_ROOT
ESP32_LIB_VERSION = 2.0.11
export ESP32_LIB_VERSION
ESP32_GCC_VERSION = esp-2021r2-patch5-8.4.0
export ESP32_GCC_VERSION
ESP32_FLASHTOOL_VERSION = 4.5.1
export ESP32_FLASHTOOL_VERSION
ARDUINO_F_CPU = 240000000L
export ARDUINO_F_CPU
ESP_BOARD_NAME = ESP32_DEV
export ESP_BOARD_NAME
ESP_FLASH_MODE = dio
export ESP_FLASH_MODE
ESP_FLASH_FREQUENCY = 80m
export ESP_FLASH_FREQUENCY
ESP_FLASH_SIZE = 4MB
export ESP_FLASH_SIZE
ESP_VARIANT_NAME = esp32
export ESP_VARIANT_NAME
ESP_PARTITION_SCHEME = default
export ESP_PARTITION_SCHEME
ESP_DEFINES = 
export ESP_DEFINES
ESP_EXTRA_FLAGS = 
export ESP_EXTRA_FLAGS
ESP_EXTRA_LIBS = 
export ESP_EXTRA_LIBS
